### PR TITLE
Move VersionParser into its own gem

### PR DESCRIPTION
**Pull request by jvanbaarsen**
We are using the VersionChecker in version.intercity.io as well. In order to
have low maintenance if there is a bug in that piece of code, I have pulled it
out into it's own gem.

### CODE REVIEW

**Comment by michiels** [comment]
@jvanbaarsen interesting! What does this VersionParser gem do?

**Comment by jvanbaarsen** [comment]
@michiels Exactly the same as the pulled out code

**Comment by michiels** [comment]
@jvanbaarsen Ah, it's more like VersionComparer instead of VersionParser. It didn't really tell me the "end benefit" based on the naming.

**Comment by jvanbaarsen** [comment]
@michiels It is mainly parsing a version that you put in. One of the side benefits is that you can compare.

**Pull request merged**
