### PR TITLE
Prepare for Docker based deployment

### PR DESCRIPTION
**Pull request by jvanbaarsen**
* We are moving to Puma
* Adding a sample nginx config

### CODE REVIEW

**Comment by michiels** [comment]
@jvanbaarsen Just interested, not disagreeing: Why Puma compared to the other options around?

**Comment by jvanbaarsen** [comment]
@michiels Wanted to give it a try. Also with the new Intercity approach, Puma will be the server of choice (because of ease of installation).

So mainly no good reasons, just interest

**Comment by michiels** [comment]
@jvanbaarsen :+1:

Just a piece of advice: Puma or other multi-threaded kind of process servers then to sometimes be a bit hard to configure if you run related services. Sometimes things need to be hacked/configured in that `on_worker_boot do` block.

**Comment by jvanbaarsen** [comment]
@michiels Yes I'm aware :) Lets see how it goes, if it is super crappy, we can switch :)

**Pull request merged**
