### PR TITLE
Refactor ServersController

### PR DESCRIPTION
**Pull request by beydogan**
Refactor ServersController by using `before_action`
Add .idea to gitignore (for RubyMine IDE)

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@beydogan Thanks for you contribution ❤️ . Can you make sure that Rubocop passing? You can check this locally by running: `bundle exec rubocop`.

**Comment by beydogan** [comment]
@jvanbaarsen sure :+1: its fixed

**Comment by jvanbaarsen** [comment]
@beydogan Ok, I'll merge this for now. I'm usually not a big fan of the before_action for setting variables. I feel it is hiding variable declaration, and you're not aware if you're setting to many instance variables. But let's see how it feels in this one place. (There is a change I'll revert down the road though).

**Comment by jvanbaarsen** [comment]
@beydogan Oh I forgot to ask, can you squash your commits?

**Comment by beydogan** [comment]
@jvanbaarsen I see what you mean but I feel DRY is more important for this kind of stuff.

And I squashed the commits.

**Comment by jvanbaarsen** [comment]
:+1: Thanks!

**Pull request merged**
