### PR TITLE
Rotate backups that are older then 2 days

### PR DESCRIPTION
**Pull request by jvanbaarsen**
Fixes: #69

### CODE REVIEW

**Comment by michiels** [comment]
@jvanbaarsen In this case, i think "rotated" means "deleted" right? Since if I understand correctly based on the code of the job, we remove all the backups older than 2 days.

**Comment by jvanbaarsen** [comment]
@michiels Yes

**Comment by jvanbaarsen** [comment]
@michiels Deleted might sound weird, like someone has actually removed the backups (A person)

**Comment by michiels** [comment]
True. 

A thought: Does it make sense to keep showing the long list of backups if they are deleted by the system? Maybe just hide those and show a message that only backups newer than two days are kept? Or do you have a reason for keeping them on the screen.

**Comment by jvanbaarsen** [comment]
@michiels For now its basically to not create a weird feeling that backups are not created. In the future that might be a good idea.

**Comment by jvanbaarsen** [comment]
@michiels Sorry I merged to quick I think. Discussion was not finished, sorry!!!

**Pull request merged**
