### PR TITLE
Schedule health_checks in their own queue and run them in Sidekiq

### PR DESCRIPTION
**Pull request by jvanbaarsen**
By adding the health_checks into their own queue, we can start/stop that queue independent of the other queues. Also it allows us to lower the priority of the queue so normal work get priority over a healthcheck.

Fixes: #111

### CODE REVIEW

**Comment by michiels** [comment]
@jvanbaarsen Can you add a bit of context to why we would want this? Do you have a reference somewhere?

**Comment by jvanbaarsen** [comment]
@michiels I want this to be running in a separate queue pool, so I can lower the priority for this. (Its more important that we run actual commands, healthchecks can be done when we have CPU cycles left for sidekiq).

**Comment by michiels** [comment]
@jvanbaarsen Ok, so conclusion is "to be able to lower priority" for that queue :)

**Comment by jvanbaarsen** [comment]
@michiels Yes! (The whole idea why sidekiq queue's are there for, to split out work :-) )

**Comment by michiels** [comment]
Sure! I didn't know that you can deprioritize queues in Sidekiq :) Also not 100% apparent from the changelog that this is the reason. I think it's good to add little notes like that since more people than just us will be reading this.

**Comment by jvanbaarsen** [comment]
:+1:

**Pull request merged**
