### PR TITLE
Remove users

### PR DESCRIPTION
**Pull request by brambokdam**
This PR makes sure that users can be destroyed.

Fixes: https://github.com/intercity/intercity-next/issues/86

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
Do we need some protection that the last user can't be deleted?

**Comment by brambokdam** [comment]
Their is a protection in the view you can't destroy yourself. :)

**Comment by jvanbaarsen** [comment]
@brambokdam What if 2 users open the page at the same time and destroy each other?

**Comment by brambokdam** [comment]
I don't think that is possible because the second user won't authenticate if the first user destroyed him or her already. I guess their will always be one first. Also you're redirected to the welcome to Intercity view if their are no users to create a new user.

**Comment by jvanbaarsen** [comment]
@brambokdam Yeah but if you get redirected you create a security hole. I think adding an extra check in the destroy action wouldn't harm. It can just be something like:

```ruby
@user.destroy if User.count > 1
```

**Comment by brambokdam** [comment]
Sure 👍

**Comment by jvanbaarsen** [comment]
@brambokdam Nice! Can you also add an entry to the CHANGELOG? After that I can merge this :-)

**Comment by jvanbaarsen** [comment]
Superseeded by #124

**Pull request closed without merging**
