### PR TITLE
Update the installation manual

### PR DESCRIPTION
**Pull request by jvanbaarsen**

### CODE REVIEW

**Comment by brambokdam** [comment]
lgtm! Looks easy to install 👍

**Comment by michiels** [comment]
Looks good in essence! Quick question, why not have the bash script also run the installer itself? Now it feels like the user needs to execute 2 separate steps where only 1 is really nessesary (just like Brew)

**Comment by jvanbaarsen** [comment]
@michiels Because I want the user to install a management CLI, and be aware of it. So for now I want to keep it this way, and see how this works. If it starts to feel wonkey, I can also have the bash script call the install step.

FYI, things I want to do with the CLI:
1) Install IC (done)
2) Update IC
3) Perform health check
4) Get diagnostic information
5) Maybe something with external backups?

**Comment by michiels** [comment]
@jvanbaarsen Allright that makes sort of sense - Personally, I don't see why people wouldn't beware of the CLI part after the installation (just like Homebrew) but I also don't think it's that an important choice at the moment so :+1:

**Pull request merged**
