### PR TITLE
Add a predeploy plugin

### PR DESCRIPTION
**Pull request by jvanbaarsen**
We need to be able to run some action before we actually launch the container,
for example we need to run migrations. This plugin allows us to do so. See:
https://github.com/michaelshobbs/dokku-app-predeploy-tasks for more information.

Fixes: #41

### CODE REVIEW

**Comment by joshuajansen** [comment]
Can you explain what `linkable` means? From this pull I understand that if a plugin is *not* linkable, than you cannot attach/detach it from your app but it should be there by default?

**Comment by jvanbaarsen** [comment]
@joshuajansen There are certain plugins that you might want to install, but they dont need to be attached to a single app. They just need to be installed on the server. That is what `linkable` is. It tells if you can link the plugin to your app after installing it on your server.

**Comment by joshuajansen** [comment]
@jvanbaarsen ah ok! So there is a difference between app plugins and server plugins?

**Comment by jvanbaarsen** [comment]
@joshuajansen Yeah, app plugins interact with the app itself, and need to be "linked", so they are basicly new Docker containers that are linked to the app container. The other plugins are plugins that just respond to certain hooks.

**Comment by jvanbaarsen** [comment]
@joshuajansen We kinda decided that this was not needed anymore, right?

**Comment by jvanbaarsen** [comment]
We fixed this by adding the following file to the project:

```ruby
# lib/tasks/run_migrations.rake
Rake::Task['assets:clean'].enhance do
  Rake::Task['db:migrate'].invoke
end
```

/cc @brambokdam

**Pull request closed without merging**
