### PR TITLE
Move the SECRET_TOKEN to an initializer

### PR DESCRIPTION
**Pull request by jvanbaarsen**
Currently you have to set the SECRET_KEY_TOKEN in the intercity-docker app.yml
file, since we are trying to move to a system where the user doesn't have to
edit anything in the app.yml, we don't want them to think about the
SECRET_KEY_TOKEN.

The reason for storing this in Redis, is that we already have the redis instance
running, and IC runs inside Docker, which doesn't provide persistent storage.

### CODE REVIEW

**Comment by brambokdam** [comment]
lgtm 👍

**Comment by michiels** [comment]
I'm not used to storing these types of "core" configuration things in a DB. But happy to see how this works!

**Comment by michiels** [comment]
@jvanbaarsen Ah one question: How can we have people convert/migrate their current key into Redis? Maybe you can check if it's stored in an ENV var and set that in Redis, and only generate a new one if there's no ENV var set?

**Comment by jvanbaarsen** [comment]
@michiels Its not really required to keep the old key around. Worst case people have to login again.

**Comment by michiels** [comment]
@jvanbaarsen Right. It's not the most future proof solutions but agree!

**Pull request merged**
