### PR TITLE
Remove the mixpanel code that was still present

### PR DESCRIPTION
**Pull request by jvanbaarsen**
Fixes: #44

### CODE REVIEW

**Comment by brambokdam** [comment]
If we are not gonna use it maybe it is also nice remove to remove the env var `MIXPANEL_TOKEN` from `.sample.env`?

**Comment by jvanbaarsen** [comment]
:+1: Good catch, somehow searching the project missed that!

**Comment by brambokdam** [comment]
Nice :shipit:

**Pull request merged**
