### PR TITLE
Redesign server installation screen

### PR DESCRIPTION
**Pull request by jvanbaarsen**
Fixes: #146 

**Old screen**
bdce729e-3491-11e6-8a26-3737c7250931

**New screen**
setup-progress

### CODE REVIEW

**Comment by brambokdam** [comment]
lgtm 👍

**Comment by joshuajansen** [comment]
Pretty! 😍

**Comment by brambokdam** [comment]
Oh and it looks really awesome!

**Comment by joshuajansen** [comment]
I might make sense to fill the progress bar until the beginning of the active step btw. Now the "in progress step" already looks completed.

**Comment by jvanbaarsen** [comment]
@joshuajansen Yeah I'm a bit in doubt about the progress bar xD Let me take a look at that :D

**Comment by jvanbaarsen** [comment]
@joshuajansen I changed it to only fill the bar when a step is actually finished. Feels way better indeed :-)

**Comment by joshuajansen** [comment]
👏

**Comment by michiels** [comment]
@jvanbaarsen wow that screen looks awesome

**Pull request merged**
